export interface MedicationGuideEntry {
  id: string;
  name: string;
  genericName: string;
  brandNames: string[];
  drugClass: string;
  category: string;
  diseasesTreated: string[];
  symptomsTreated: string[];
  chemicalFormula: string;
  molecularWeight: string;
  mechanismOfAction: string;
  typicalDosage: string;
  onset: string;
  duration: string;
  sideEffects: string[];
  interactions: string[];
  contraindications: string[];
  isPrescription: boolean;
  pregnancyRisk: string;
  alcoholInteraction: string;
}

export const MEDICATION_GUIDE: MedicationGuideEntry[] = [
  {
    id: "paracetamol",
    name: "Paracetamol",
    genericName: "Acetaminophen",
    brandNames: ["Crocin", "Tylenol", "Calpol", "Dolo", "Panadol"],
    drugClass: "Analgesic / Antipyretic",
    category: "Pain & Fever",
    diseasesTreated: ["Fever", "Headache", "Cold & Flu", "Body ache", "Toothache", "Menstrual cramps"],
    symptomsTreated: ["Fever", "Headache", "Body ache", "Mild to moderate pain", "Sore throat pain"],
    chemicalFormula: "C8H9NO2",
    molecularWeight: "151.16 g/mol",
    mechanismOfAction: "Inhibits cyclooxygenase (COX) enzymes in the central nervous system, reducing prostaglandin synthesis in the brain, which lowers the body's fever set-point and pain signaling. It has minimal peripheral anti-inflammatory effect.",
    typicalDosage: "500-1000 mg every 4-6 hours, max 4000 mg/day",
    onset: "30-60 minutes",
    duration: "4-6 hours",
    sideEffects: ["Nausea", "Rash", "Liver damage at high doses", "Rare allergic reactions"],
    interactions: ["Alcohol (increases liver toxicity)", "Warfarin (increases bleeding risk)", "Rifampin"],
    contraindications: ["Severe liver disease", "Hepatic failure", "Known allergy to paracetamol"],
    isPrescription: false,
    pregnancyRisk: "Category B — generally considered safe",
    alcoholInteraction: "Yes — avoid with chronic alcohol use",
  },
  {
    id: "ibuprofen",
    name: "Ibuprofen",
    genericName: "Ibuprofen",
    brandNames: ["Brufen", "Advil", "Motrin", "Combiflam (with paracetamol)"],
    drugClass: "NSAID (Non-Steroidal Anti-Inflammatory Drug)",
    category: "Pain, Fever & Inflammation",
    diseasesTreated: ["Fever", "Headache", "Muscle pain", "Arthritis", "Period pain", "Dental pain", "Inflammatory conditions"],
    symptomsTreated: ["Fever", "Inflammation", "Joint pain", "Muscle ache", "Swelling", "Menstrual cramps"],
    chemicalFormula: "C13H18O2",
    molecularWeight: "206.28 g/mol",
    mechanismOfAction: "Non-selectively inhibits COX-1 and COX-2 enzymes, blocking prostaglandin production. Reduces inflammation, fever, and pain by lowering prostaglandin-mediated vasodilation and pain sensitization.",
    typicalDosage: "200-400 mg every 4-6 hours with food, max 1200 mg/day OTC",
    onset: "20-30 minutes",
    duration: "4-6 hours",
    sideEffects: ["Stomach upset", "Heartburn", "Nausea", "Increased bleeding risk", "Kidney issues with long-term use"],
    interactions: ["Aspirin (reduces cardioprotection)", "Warfarin (bleeding risk)", "ACE inhibitors", "Diuretics", "Corticosteroids"],
    contraindications: ["Peptic ulcer disease", "Severe kidney disease", "Aspirin allergy", "Third trimester pregnancy"],
    isPrescription: false,
    pregnancyRisk: "Avoid in third trimester",
    alcoholInteraction: "Yes — increases stomach bleeding risk",
  },
  {
    id: "aspirin",
    name: "Aspirin",
    genericName: "Acetylsalicylic Acid",
    brandNames: ["Disprin", "Bayer Aspirin", "Ecospirin"],
    drugClass: "NSAID / Antiplatelet",
    category: "Pain, Fever & Heart Health",
    diseasesTreated: ["Headache", "Mild pain", "Fever", "Heart attack prevention", "Stroke prevention"],
    symptomsTreated: ["Headache", "Mild pain", "Fever", "Inflammation"],
    chemicalFormula: "C9H8O4",
    molecularWeight: "180.16 g/mol",
    mechanismOfAction: "Irreversibly inhibits COX-1, blocking thromboxane A2 production in platelets, reducing platelet aggregation. At analgesic doses also inhibits COX-2 reducing pain and fever.",
    typicalDosage: "Pain: 325-650 mg every 4 hours. Cardiac: 75-100 mg daily",
    onset: "30 minutes",
    duration: "4-6 hours (platelet effect 7-10 days)",
    sideEffects: ["Stomach irritation", "Heartburn", "Bleeding risk", "Tinnitus at high doses", "Reye's syndrome in children"],
    interactions: ["Warfarin (severe bleeding risk)", "Ibuprofen (reduces antiplatelet effect)", "Other NSAIDs", "Alcohol", "Antacids"],
    contraindications: ["Peptic ulcers", "Bleeding disorders", "Children under 16 (Reye's syndrome)", "Aspirin allergy"],
    isPrescription: false,
    pregnancyRisk: "Avoid in third trimester",
    alcoholInteraction: "Yes — increases bleeding risk",
  },
  {
    id: "amoxicillin",
    name: "Amoxicillin",
    genericName: "Amoxicillin",
    brandNames: ["Mox", "Amoxil", "Moxikind", "Augmentin (with clavulanate)"],
    drugClass: "Penicillin Antibiotic",
    category: "Antibiotics",
    diseasesTreated: ["Tonsillitis", "Ear infection", "Sinusitis", "Pneumonia", "Urinary tract infection", "Dental infections"],
    symptomsTreated: ["Bacterial throat pain", "Ear pain", "Cough with bacterial infection", "Fever from bacterial infection", "Sinus congestion from infection"],
    chemicalFormula: "C16H19N3O5S",
    molecularWeight: "365.40 g/mol",
    mechanismOfAction: "Beta-lactam antibiotic that inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins, causing cell lysis in actively dividing bacteria. Bactericidal against many gram-positive and some gram-negative organisms.",
    typicalDosage: "250-500 mg every 8 hours, or 500-875 mg every 12 hours",
    onset: "1-2 hours",
    duration: "7-10 days typical course",
    sideEffects: ["Diarrhea", "Nausea", "Rash", "Yeast infection", "Allergic reactions (rare, can be severe)"],
    interactions: ["Methotrexate", "Warfarin (increased bleeding)", "Oral contraceptives (may reduce effectiveness)", "Allopurinol"],
    contraindications: ["Penicillin allergy", "History of severe allergic reaction to beta-lactams"],
    isPrescription: true,
    pregnancyRisk: "Category B — generally considered safe",
    alcoholInteraction: "No direct interaction, but avoid during illness",
  },
  {
    id: "azithromycin",
    name: "Azithromycin",
    genericName: "Azithromycin",
    brandNames: ["Azithral", "Zithromax", "Azee"],
    drugClass: "Macrolide Antibiotic",
    category: "Antibiotics",
    diseasesTreated: ["Respiratory infections", "Pneumonia", "Bronchitis", "Sinusitis", "Skin infections", "STIs"],
    symptomsTreated: ["Cough from bacterial infection", "Fever", "Chest congestion", "Sore throat"],
    chemicalFormula: "C38H72N2O12",
    molecularWeight: "748.98 g/mol",
    mechanismOfAction: "Binds to the 50S ribosomal subunit, inhibiting bacterial protein synthesis. Bacteriostatic; concentrates in tissues and phagocytes allowing short 3-5 day courses.",
    typicalDosage: "500 mg on day 1, then 250 mg days 2-5",
    onset: "2-4 hours",
    duration: "24 hours per dose, 3-5 day course",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal pain", "Headache", "QT prolongation (rare)", "Liver enzyme elevation"],
    interactions: ["Antacids containing magnesium/aluminum (separate by 2 hours)", "Warfarin", "Digoxin", "Medications that prolong QT interval"],
    contraindications: ["History of cholestatic jaundice with macrolides", "QT prolongation"],
    isPrescription: true,
    pregnancyRisk: "Category B — generally considered safe",
    alcoholInteraction: "Not recommended",
  },
  {
    id: "metformin",
    name: "Metformin",
    genericName: "Metformin Hydrochloride",
    brandNames: ["Glycomet", "Glucophage", "Riomet", "Obimet"],
    drugClass: "Biguanide Antidiabetic",
    category: "Diabetes",
    diseasesTreated: ["Type 2 diabetes", "Prediabetes", "PCOS"],
    symptomsTreated: ["High blood sugar", "Insulin resistance", "Excessive thirst", "Frequent urination"],
    chemicalFormula: "C4H11N5",
    molecularWeight: "129.16 g/mol",
    mechanismOfAction: "Activates AMP-activated protein kinase (AMPK), decreasing hepatic glucose production, reducing intestinal glucose absorption, and improving insulin sensitivity in peripheral tissues. Does not cause hypoglycemia alone.",
    typicalDosage: "500-2000 mg/day in divided doses with meals",
    onset: "3-7 days for effect",
    duration: "24 hours per dose",
    sideEffects: ["Nausea", "Diarrhea", "Abdominal discomfort", "Metallic taste", "Vitamin B12 deficiency (long-term)", "Lactic acidosis (rare)"],
    interactions: ["Contrast dye (temporarily stop)", "Alcohol (lactic acidosis risk)", "Cimetidine", "Carbonic anhydrase inhibitors"],
    contraindications: ["Severe kidney disease (eGFR <30)", "Metabolic acidosis", "Hypoxia", "Severe heart failure"],
    isPrescription: true,
    pregnancyRisk: "Generally safe, used in gestational diabetes",
    alcoholInteraction: "Yes — avoid heavy alcohol (lactic acidosis risk)",
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    genericName: "Atorvastatin Calcium",
    brandNames: ["Lipitor", "Atorva", "Atorlip", "Storvas"],
    drugClass: "Statin (HMG-CoA Reductase Inhibitor)",
    category: "Cholesterol",
    diseasesTreated: ["High cholesterol", "High LDL", "Cardiovascular disease prevention"],
    symptomsTreated: ["Elevated LDL cholesterol", "High total cholesterol", "Elevated triglycerides"],
    chemicalFormula: "C33H35FN2O5",
    molecularWeight: "558.64 g/mol",
    mechanismOfAction: "Competitively inhibits HMG-CoA reductase, the rate-limiting enzyme in hepatic cholesterol synthesis. Increases LDL receptor expression, lowering plasma LDL by 30-50%.",
    typicalDosage: "10-80 mg once daily, usually in the evening",
    onset: "2-4 weeks for lipid changes",
    duration: "24 hours per dose",
    sideEffects: ["Muscle pain", "Headache", "Digestive issues", "Liver enzyme elevation", "Rhabdomyolysis (rare)", "Increased blood sugar"],
    interactions: ["Grapefruit juice (avoid large amounts)", "Warfarin", "Clarithromycin", "Cyclosporine", "Amiodarone", "Colchicine"],
    contraindications: ["Active liver disease", "Pregnancy", "Breastfeeding"],
    isPrescription: true,
    pregnancyRisk: "Contraindicated",
    alcoholInteraction: "Limit alcohol (liver stress)",
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    genericName: "Amlodipine Besylate",
    brandNames: ["Amlong", "Norvasc", "Amlopin", "Amlocard"],
    drugClass: "Calcium Channel Blocker",
    category: "Blood Pressure",
    diseasesTreated: ["Hypertension", "Angina", "Coronary artery disease"],
    symptomsTreated: ["High blood pressure", "Chest pain from angina", "Shortness of breath"],
    chemicalFormula: "C20H25ClN2O5",
    molecularWeight: "408.88 g/mol",
    mechanismOfAction: "Blocks L-type calcium channels in vascular smooth muscle, causing vasodilation of peripheral arteries. Reduces peripheral vascular resistance, lowering blood pressure. Also dilates coronary arteries.",
    typicalDosage: "2.5-10 mg once daily",
    onset: "1-2 hours, full effect 7-14 days",
    duration: "24 hours per dose",
    sideEffects: ["Ankle swelling", "Flushing", "Headache", "Dizziness", "Palpitations", "Fatigue"],
    interactions: ["Grapefruit juice", "Simvastatin (limit to 20mg)", "CYP3A4 inhibitors like ketoconazole", "Cyclosporine"],
    contraindications: ["Severe aortic stenosis", "Cardiogenic shock", "Hypotension"],
    isPrescription: true,
    pregnancyRisk: "Avoid unless clearly needed",
    alcoholInteraction: "Yes — can worsen hypotension",
  },
  {
    id: "losartan",
    name: "Losartan",
    genericName: "Losartan Potassium",
    brandNames: ["Losar", "Cozaar", "Losakind", "Repace"],
    drugClass: "ARB (Angiotensin II Receptor Blocker)",
    category: "Blood Pressure & Kidney Protection",
    diseasesTreated: ["Hypertension", "Diabetic nephropathy", "Heart failure"],
    symptomsTreated: ["High blood pressure", "Proteinuria in diabetes", "Heart failure symptoms"],
    chemicalFormula: "C22H23ClN6O",
    molecularWeight: "422.92 g/mol",
    mechanismOfAction: "Selectively blocks angiotensin II AT1 receptors, preventing vasoconstriction and aldosterone release. Reduces blood pressure and provides renal protection by reducing intraglomerular pressure.",
    typicalDosage: "25-100 mg once or twice daily",
    onset: "1-2 hours, full effect 3-6 weeks",
    duration: "24 hours per dose",
    sideEffects: ["Dizziness", "Headache", "Hyperkalemia", "Cough (less common than ACE inhibitors)", "Renal impairment"],
    interactions: ["Potassium supplements", "Potassium-sparing diuretics", "Lithium", "NSAIDs (reduce effect, harm kidneys)"],
    contraindications: ["Pregnancy", "Bilateral renal artery stenosis", "Severe liver disease"],
    isPrescription: true,
    pregnancyRisk: "Contraindicated",
    alcoholInteraction: "Yes — can worsen hypotension",
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    genericName: "Lisinopril",
    brandNames: ["Lisinopril", "Zestril", "Prinivil", "Lipril"],
    drugClass: "ACE Inhibitor",
    category: "Blood Pressure & Heart Failure",
    diseasesTreated: ["Hypertension", "Heart failure", "Post-heart attack", "Diabetic nephropathy"],
    symptomsTreated: ["High blood pressure", "Heart failure symptoms", "Proteinuria"],
    chemicalFormula: "C21H31N3O5",
    molecularWeight: "405.49 g/mol",
    mechanismOfAction: "Inhibits angiotensin-converting enzyme (ACE), preventing angiotensin II formation. Causes vasodilation, reduces aldosterone, lowers blood pressure and afterload on the heart.",
    typicalDosage: "5-40 mg once daily",
    onset: "1 hour, full effect 4-6 weeks",
    duration: "24 hours per dose",
    sideEffects: ["Dry cough (common)", "Dizziness", "Hyperkalemia", "Angioedema (rare, serious)", "Elevated creatinine"],
    interactions: ["Potassium supplements", "NSAIDs (reduce effect)", "Lithium", "Diuretics", "Sacubitril/valsartan"],
    contraindications: ["Pregnancy", "History of angioedema", "Bilateral renal artery stenosis"],
    isPrescription: true,
    pregnancyRisk: "Contraindicated",
    alcoholInteraction: "Yes — can worsen hypotension",
  },
  {
    id: "omeprazole",
    name: "Omeprazole",
    genericName: "Omeprazole",
    brandNames: ["Ocid", "Losec", "Prilosec", "Omez"],
    drugClass: "Proton Pump Inhibitor (PPI)",
    category: "Acidity & GERD",
    diseasesTreated: ["GERD", "Acid reflux", "Peptic ulcer", "Gastritis", "Zollinger-Ellison syndrome"],
    symptomsTreated: ["Heartburn", "Acid reflux", "Stomach pain", "Acid regurgitation", "Bloating"],
    chemicalFormula: "C17H19N3O3S",
    molecularWeight: "345.42 g/mol",
    mechanismOfAction: "Irreversibly inhibits H+/K+-ATPase (proton pump) in gastric parietal cells, blocking the final step of gastric acid secretion. Reduces both basal and stimulated acid production.",
    typicalDosage: "20-40 mg once daily before breakfast",
    onset: "1-2 hours, full effect 3-4 days",
    duration: "24-48 hours per dose",
    sideEffects: ["Headache", "Nausea", "Diarrhea", "Long-term: vitamin B12 deficiency, magnesium deficiency, increased fracture risk", "C. difficile risk"],
    interactions: ["Clopidogrel (reduced activation)", "Warfarin", "Diazepam", "Phenytoin", "Methotrexate"],
    contraindications: ["Concomitant rilpivirine", "Severe hepatic impairment"],
    isPrescription: false,
    pregnancyRisk: "Generally considered safe (Category B/C)",
    alcoholInteraction: "Can worsen symptoms",
  },
  {
    id: "cetirizine",
    name: "Cetirizine",
    genericName: "Cetirizine Hydrochloride",
    brandNames: ["Zyrtec", "Cetiriz", "Alerid", "Cetzine"],
    drugClass: "Second-generation Antihistamine",
    category: "Allergy",
    diseasesTreated: ["Allergic rhinitis", "Hay fever", "Hives", "Dust/pollen allergy", "Pet allergy"],
    symptomsTreated: ["Sneezing", "Runny nose", "Itchy eyes", "Itchy skin", "Hives", "Nasal congestion"],
    chemicalFormula: "C21H25ClN2O3",
    molecularWeight: "388.89 g/mol",
    mechanismOfAction: "Selective peripheral H1 receptor antagonist. Blocks histamine binding, reducing allergic symptoms without significant central sedation compared to first-generation antihistamines.",
    typicalDosage: "10 mg once daily",
    onset: "1 hour",
    duration: "24 hours per dose",
    sideEffects: ["Mild drowsiness", "Dry mouth", "Headache", "Fatigue", "Dizziness"],
    interactions: ["Alcohol", "Sedatives", "CNS depressants"],
    contraindications: ["Severe kidney disease (adjust dose)", "Known hypersensitivity"],
    isPrescription: false,
    pregnancyRisk: "Generally considered safe",
    alcoholInteraction: "Yes — increased drowsiness",
  },
  {
    id: "loratadine",
    name: "Loratadine",
    genericName: "Loratadine",
    brandNames: ["Claritin", "Lorfast", "Loratin", "Lorano"],
    drugClass: "Second-generation Antihistamine",
    category: "Allergy",
    diseasesTreated: ["Allergic rhinitis", "Hay fever", "Hives", "Seasonal allergies"],
    symptomsTreated: ["Sneezing", "Runny nose", "Itchy eyes", "Itchy throat", "Hives"],
    chemicalFormula: "C22H23ClN2O2",
    molecularWeight: "382.89 g/mol",
    mechanismOfAction: "Selective peripheral H1 receptor antagonist with low CNS penetration. Blocks histamine effects on receptors, relieving allergic symptoms with minimal sedation.",
    typicalDosage: "10 mg once daily",
    onset: "1-3 hours",
    duration: "24 hours per dose",
    sideEffects: ["Headache", "Dry mouth", "Fatigue (uncommon)", "Nervousness (rare)"],
    interactions: ["Ketoconazole", "Erythromycin (increased levels)", "Cimetidine"],
    contraindications: ["Known hypersensitivity to loratadine"],
    isPrescription: false,
    pregnancyRisk: "Generally considered safe",
    alcoholInteraction: "Minimal, but caution advised",
  },
  {
    id: "salbutamol",
    name: "Salbutamol",
    genericName: "Salbutamol / Albuterol",
    brandNames: ["Asthalin", "Ventolin", "Proventil", "Salma"],
    drugClass: "Short-acting Beta-2 Agonist (SABA)",
    category: "Asthma & Respiratory",
    diseasesTreated: ["Asthma", "COPD", "Exercise-induced bronchospasm", "Bronchitis with bronchospasm"],
    symptomsTreated: ["Wheezing", "Shortness of breath", "Chest tightness", "Cough with bronchospasm", "Difficulty breathing"],
    chemicalFormula: "C13H21NO3",
    molecularWeight: "239.31 g/mol",
    mechanismOfAction: "Selectively stimulates beta-2 adrenergic receptors in bronchial smooth muscle, activating adenylate cyclase and increasing cAMP. Causes rapid bronchodilation and bronchial smooth muscle relaxation.",
    typicalDosage: "1-2 puffs (100-200 mcg) every 4-6 hours as needed via inhaler",
    onset: "5-15 minutes",
    duration: "4-6 hours",
    sideEffects: ["Tremor", "Palpitations", "Headache", "Nervousness", "Muscle cramps", "Increased heart rate"],
    interactions: ["Beta-blockers (reduce effect)", "Diuretics", "MAO inhibitors", "Tricyclic antidepressants"],
    contraindications: ["Known hypersensitivity", "Severe cardiovascular disease (caution)"],
    isPrescription: true,
    pregnancyRisk: "Generally considered safe",
    alcoholInteraction: "No significant interaction",
  },
  {
    id: "sertraline",
    name: "Sertraline",
    genericName: "Sertraline Hydrochloride",
    brandNames: ["Zoloft", "Serlift", "Zosert", "Setra"],
    drugClass: "SSRI (Selective Serotonin Reuptake Inhibitor)",
    category: "Mental Health",
    diseasesTreated: ["Depression", "Anxiety", "Panic disorder", "OCD", "PTSD", "Social anxiety"],
    symptomsTreated: ["Low mood", "Anxiety", "Panic attacks", "Intrusive thoughts", "Irritability", "Poor concentration"],
    chemicalFormula: "C17H17Cl2N",
    molecularWeight: "306.23 g/mol",
    mechanismOfAction: "Selectively inhibits serotonin (5-HT) reuptake in the synaptic cleft, increasing serotonin availability in the brain. Modulates mood, anxiety, and emotional regulation pathways.",
    typicalDosage: "25-50 mg once daily, max 200 mg/day",
    onset: "2-6 weeks for therapeutic effect",
    duration: "24 hours per dose",
    sideEffects: ["Nausea", "Diarrhea", "Insomnia", "Headache", "Sexual dysfunction", "Weight changes", "Serotonin syndrome (rare, serious)"],
    interactions: ["MAO inhibitors (serotonin syndrome — contraindicated)", "Tramadol", "NSAIDs (bleeding risk)", "Warfarin", "St. John's Wort"],
    contraindications: ["MAO inhibitor use within 14 days", "Known hypersensitivity"],
    isPrescription: true,
    pregnancyRisk: "Caution — discuss risks/benefits",
    alcoholInteraction: "Yes — avoid (CNS effects)",
  },
  {
    id: "levothyroxine",
    name: "Levothyroxine",
    genericName: "Levothyroxine Sodium",
    brandNames: ["Thyronorm", "Eltroxin", "Synthroid", "Thyrox"],
    drugClass: "Thyroid Hormone Replacement",
    category: "Thyroid",
    diseasesTreated: ["Hypothyroidism", "Thyroid hormone deficiency", "Goiter", "Post-thyroidectomy"],
    symptomsTreated: ["Fatigue", "Weight gain", "Cold intolerance", "Constipation", "Hair thinning", "Dry skin"],
    chemicalFormula: "C15H11I4NO4",
    molecularWeight: "776.87 g/mol",
    mechanismOfAction: "Synthetic thyroid hormone (T4) that binds to thyroid hormone receptors, regulating cellular metabolism, growth, and development. Restores euthyroid state in hypothyroid patients.",
    typicalDosage: "25-200 mcg once daily on empty stomach, 30-60 min before breakfast",
    onset: "3-5 days",
    duration: "7 days per dose",
    sideEffects: ["Palpitations", "Anxiety", "Insomnia", "Weight loss (if over-replaced)", "Heat intolerance", "Tremor"],
    interactions: ["Iron/calcium supplements (separate by 4 hours)", "Antacids", "Warfarin (increases effect)", "PPIs", "Estrogen"],
    contraindications: ["Untreated thyrotoxicosis", "Adrenal insufficiency (untreated)", "Recent myocardial infarction"],
    isPrescription: true,
    pregnancyRisk: "Essential during pregnancy — do not stop",
    alcoholInteraction: "No significant interaction",
  },
  {
    id: "hydrochlorothiazide",
    name: "Hydrochlorothiazide",
    genericName: "Hydrochlorothiazide",
    brandNames: ["Hygroton", "Hydrozide", "Esidrix", "HCTZ"],
    drugClass: "Thiazide Diuretic",
    category: "Blood Pressure & Edema",
    diseasesTreated: ["Hypertension", "Edema", "Congestive heart failure", "Kidney stones (calcium)"],
    symptomsTreated: ["High blood pressure", "Swelling", "Fluid retention"],
    chemicalFormula: "C7H8ClN3O4S2",
    molecularWeight: "297.74 g/mol",
    mechanismOfAction: "Inhibits sodium-chloride cotransporter in the distal convoluted tubule, increasing sodium and water excretion. Reduces plasma volume initially and peripheral resistance long-term.",
    typicalDosage: "12.5-25 mg once daily",
    onset: "2 hours, full effect 4-6 weeks",
    duration: "6-12 hours",
    sideEffects: ["Low potassium", "Low sodium", "Dizziness", "Increased blood sugar", "Increased uric acid", "Dehydration"],
    interactions: ["Lithium (increases levels)", "Digoxin", "Other blood pressure medications (additive effect)", "NSAIDs (reduce effect)"],
    contraindications: ["Anuria", "Severe kidney disease", "Sulfa allergy"],
    isPrescription: true,
    pregnancyRisk: "Caution — avoid in pregnancy unless necessary",
    alcoholInteraction: "Yes — can worsen hypotension/dehydration",
  },
  {
    id: "warfarin",
    name: "Warfarin",
    genericName: "Warfarin Sodium",
    brandNames: ["Coumadin", "Uniwarfin", "Thrombostat"],
    drugClass: "Vitamin K Antagonist (Anticoagulant)",
    category: "Blood Thinner",
    diseasesTreated: ["Atrial fibrillation", "Deep vein thrombosis", "Pulmonary embolism", "Mechanical heart valves", "Stroke prevention"],
    symptomsTreated: ["Prevents blood clots", "Reduces stroke risk", "Prevents clot recurrence"],
    chemicalFormula: "C19H16O4",
    molecularWeight: "308.33 g/mol",
    mechanismOfAction: "Inhibits vitamin K epoxide reductase, blocking synthesis of vitamin K-dependent clotting factors (II, VII, IX, X) in the liver. Reduces blood clotting ability, requiring INR monitoring.",
    typicalDosage: "1-10 mg once daily, dose adjusted to INR target",
    onset: "36-72 hours",
    duration: "2-5 days per dose",
    sideEffects: ["Bleeding", "Bruising", "Hair loss", "Purple toes syndrome", "Skin necrosis (rare)"],
    interactions: ["Many — NSAIDs (bleeding risk)", "Antibiotics", "Ibuprofen", "Aspirin", "Vitamin K rich foods (leafy greens)", "Alcohol", "Amiodarone"],
    contraindications: ["Active bleeding", "Recent surgery", "Pregnancy", "Severe liver disease", "Uncontrolled hypertension"],
    isPrescription: true,
    pregnancyRisk: "Contraindicated",
    alcoholInteraction: "Yes — significantly affects INR",
  },
  {
    id: "prednisone",
    name: "Prednisone",
    genericName: "Prednisone",
    brandNames: ["Wysolone", "Deltasone", "Omnacortil", "Prednisol"],
    drugClass: "Corticosteroid",
    category: "Inflammation & Autoimmune",
    diseasesTreated: ["Severe allergies", "Asthma exacerbation", "Autoimmune diseases", "Inflammatory conditions", "COPD exacerbation", "Skin conditions"],
    symptomsTreated: ["Severe inflammation", "Allergic reactions", "Swelling", "Itching", "Wheezing", "Joint pain from inflammation"],
    chemicalFormula: "C21H26O5",
    molecularWeight: "358.43 g/mol",
    mechanismOfAction: "Binds to glucocorticoid receptors, modulating gene transcription. Suppresses inflammatory mediators (cytokines, prostaglandins) and immune cell function. Broad anti-inflammatory and immunosuppressive effects.",
    typicalDosage: "5-60 mg daily, usually tapered",
    onset: "Hours to days depending on dose",
    duration: "Dose-dependent",
    sideEffects: ["Weight gain", "High blood sugar", "Mood changes", "Insomnia", "Increased appetite", "Osteoporosis (long-term)", "Immunosuppression"],
    interactions: ["NSAIDs (GI bleeding risk)", "Warfarin", "Diuretics (potassium loss)", "Vaccines (avoid live vaccines)", "Diabetes medications (may need dose increase)"],
    contraindications: ["Systemic fungal infections", "Live vaccines"],
    isPrescription: true,
    pregnancyRisk: "Use with caution — discuss with doctor",
    alcoholInteraction: "Caution — GI bleeding risk",
  },
  {
    id: "domperidone",
    name: "Domperidone",
    genericName: "Domperidone",
    brandNames: ["Domstal", "Motilium", "Domper", "Normoxin"],
    drugClass: "Dopamine Antagonist (Prokinetic)",
    category: "Nausea & Digestion",
    diseasesTreated: ["Nausea", "Vomiting", "Gastroparesis", "Acid reflux", "Bloating", "Indigestion"],
    symptomsTreated: ["Nausea", "Vomiting", "Bloating", "Fullness after meals", "Abdominal discomfort", "Acid reflux"],
    chemicalFormula: "C22H24ClN5O2",
    molecularWeight: "425.91 g/mol",
    mechanismOfAction: "Blocks dopamine D2 receptors in the chemoreceptor trigger zone and gastrointestinal tract, increasing gastric motility and emptying while reducing nausea and vomiting.",
    typicalDosage: "10 mg every 6-8 hours before meals, max 30-40 mg/day",
    onset: "30-60 minutes",
    duration: "6-8 hours",
    sideEffects: ["Dry mouth", "Headache", "QT prolongation (high doses)", "Increased prolactin (breast tenderness)", "Drowsiness"],
    interactions: ["Ketoconazole", "Erythromycin", "Medications prolonging QT interval", "Anticholinergics"],
    contraindications: ["Prolactinoma", "Severe liver disease", "Cardiac QT prolongation", "Under 12 years (in some regions)"],
    isPrescription: true,
    pregnancyRisk: "Caution — use only if clearly needed",
    alcoholInteraction: "Caution advised",
  },
  {
    id: "ranitidine",
    name: "Ranitidine",
    genericName: "Ranitidine Hydrochloride",
    brandNames: ["Zinetac", "Rantac", "Zantac", "Acicard"],
    drugClass: "H2 Receptor Antagonist",
    category: "Acidity & GERD",
    diseasesTreated: ["GERD", "Acid reflux", "Peptic ulcer", "Gastritis", "Heartburn"],
    symptomsTreated: ["Heartburn", "Acid regurgitation", "Stomach pain", "Sour taste", "Indigestion"],
    chemicalFormula: "C13H22N4O3S",
    molecularWeight: "314.40 g/mol",
    mechanismOfAction: "Competitively blocks histamine H2 receptors on gastric parietal cells, reducing basal and stimulated gastric acid secretion. Note: largely withdrawn globally due to NDMA impurity concerns; omeprazole is preferred.",
    typicalDosage: "150 mg twice daily or 300 mg at bedtime (historically)",
    onset: "30-60 minutes",
    duration: "8-12 hours",
    sideEffects: ["Headache", "Dizziness", "Constipation", "Diarrhea", "Fatigue"],
    interactions: ["Ketoconazole (reduces absorption)", "Warfarin", "Glipizide", "Procainamide"],
    contraindications: ["Known hypersensitivity", "History of NDMA-related concerns — consult doctor"],
    isPrescription: false,
    pregnancyRisk: "Category B — generally considered safe",
    alcoholInteraction: "Caution advised",
  },
  {
    id: "insulin",
    name: "Insulin (Human)",
    genericName: "Human Insulin",
    brandNames: ["Huminsulin", "Novolin", "Actrapid", "Mixtard", "Lantus (glargine)"],
    drugClass: "Insulin",
    category: "Diabetes",
    diseasesTreated: ["Type 1 diabetes", "Type 2 diabetes (advanced)", "Diabetic ketoacidosis", "Gestational diabetes"],
    symptomsTreated: ["High blood sugar", "Excessive thirst", "Frequent urination", "Blurred vision", "Fatigue"],
    chemicalFormula: "C257H383N65O77S6",
    molecularWeight: "5808 g/mol",
    mechanismOfAction: "Binds to insulin receptors, promoting glucose uptake into muscle and adipose tissue, inhibiting hepatic glucose production, and promoting glycogen synthesis. Replaces deficient endogenous insulin.",
    typicalDosage: "Highly individualized; basal 0.1-0.5 U/kg/day plus prandial dosing",
    onset: "Rapid: 10-15 min; Regular: 30 min; Basal: 1-2 hours",
    duration: "Rapid: 3-5h; Regular: 6-8h; Basal: 24h",
    sideEffects: ["Hypoglycemia (low blood sugar)", "Weight gain", "Injection site reactions", "Lipodystrophy", "Edema"],
    interactions: ["Beta-blockers (mask hypoglycemia)", "Corticosteroids (raise blood sugar)", "Alcohol (hypoglycemia risk)", "Thiazides"],
    contraindications: ["Hypoglycemia", "Known hypersensitivity to insulin"],
    isPrescription: true,
    pregnancyRisk: "Safe and necessary in pregnancy",
    alcoholInteraction: "Yes — increases hypoglycemia risk",
  },
  {
    id: "metoclopramide",
    name: "Metoclopramide",
    genericName: "Metoclopramide Hydrochloride",
    brandNames: ["Perinorm", "Reglan", "Maxolon", "Emnorm"],
    drugClass: "Dopamine Antagonist (Prokinetic)",
    category: "Nausea & Migraine",
    diseasesTreated: ["Nausea", "Vomiting", "Gastroparesis", "Migraine-associated nausea", "Post-surgical nausea"],
    symptomsTreated: ["Nausea", "Vomiting", "Bloating", "Fullness", "Stomach discomfort"],
    chemicalFormula: "C14H22ClN3O2",
    molecularWeight: "299.80 g/mol",
    mechanismOfAction: "Blocks dopamine D2 receptors in the chemoreceptor trigger zone, reducing nausea. Increases lower esophageal sphincter tone and gastric emptying.",
    typicalDosage: "10 mg every 6-8 hours before meals",
    onset: "30-60 minutes",
    duration: "1-2 hours",
    sideEffects: ["Drowsiness", "Dystonia (rare)", "Restlessness", "Fatigue", "Tardive dyskinesia (long-term)"],
    interactions: ["MAO inhibitors", "Tricyclic antidepressants", "Alcohol", "Sedatives"],
    contraindications: ["Parkinson's disease", "GI obstruction", "Pheochromocytoma", "Epilepsy"],
    isPrescription: true,
    pregnancyRisk: "Generally considered safe, use if clearly needed",
    alcoholInteraction: "Yes — increased sedation",
  },
  {
    id: "cetirizine-tab",
    name: "Fexofenadine",
    genericName: "Fexofenadine",
    brandNames: ["Allegra", "Fexo", "Telfast", "Algraf"],
    drugClass: "Second-generation Antihistamine",
    category: "Allergy",
    diseasesTreated: ["Allergic rhinitis", "Hay fever", "Hives", "Seasonal allergies"],
    symptomsTreated: ["Sneezing", "Runny nose", "Itchy eyes", "Hives", "Nasal congestion"],
    chemicalFormula: "C32H39NO4",
    molecularWeight: "501.66 g/mol",
    mechanismOfAction: "Selective peripheral H1 receptor antagonist that does not cross the blood-brain barrier significantly, so it is non-sedating. Blocks histamine-mediated allergic symptoms.",
    typicalDosage: "120-180 mg once daily",
    onset: "1-3 hours",
    duration: "24 hours per dose",
    sideEffects: ["Headache", "Dizziness", "Dry mouth", "Nausea (rare)"],
    interactions: ["Fruit juices (orange, grapefruit, apple — reduce absorption)", "Antacids (aluminum/magnesium)", "Ketoconazole"],
    contraindications: ["Known hypersensitivity to fexofenadine"],
    isPrescription: false,
    pregnancyRisk: "Generally considered safe",
    alcoholInteraction: "Minimal interaction",
  },
  {
    id: "diclofenac",
    name: "Diclofenac",
    genericName: "Diclofenac Sodium",
    brandNames: ["Voveran", "Voltaren", "Diclogesic", "Cataflam"],
    drugClass: "NSAID",
    category: "Pain & Inflammation",
    diseasesTreated: ["Arthritis", "Musculoskeletal pain", "Inflammation", "Post-injury pain", "Migraine"],
    symptomsTreated: ["Joint pain", "Back pain", "Muscle pain", "Inflammation", "Swelling", "Pain after injury"],
    chemicalFormula: "C14H11Cl2NO2",
    molecularWeight: "296.15 g/mol",
    mechanismOfAction: "Non-selectively inhibits COX-1 and COX-2, reducing prostaglandin synthesis. Provides potent anti-inflammatory, analgesic, and antipyretic effects.",
    typicalDosage: "50 mg 2-3 times daily, or 75 mg twice daily",
    onset: "30 minutes",
    duration: "6-8 hours",
    sideEffects: ["Stomach pain", "Heartburn", "Nausea", "Bleeding risk", "Kidney issues", "Cardiovascular risk (long-term)"],
    interactions: ["Warfarin (bleeding risk)", "Aspirin", "Other NSAIDs", "ACE inhibitors", "Diuretics", "Methotrexate"],
    contraindications: ["Peptic ulcer", "Heart failure", "Kidney disease", "Aspirin allergy", "Third trimester pregnancy"],
    isPrescription: true,
    pregnancyRisk: "Avoid in third trimester",
    alcoholInteraction: "Yes — increases GI bleeding",
  },
];

export function searchMedicationGuide(query: string): MedicationGuideEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return MEDICATION_GUIDE;

  return MEDICATION_GUIDE.filter((med) => {
    return (
      med.name.toLowerCase().includes(q) ||
      med.genericName.toLowerCase().includes(q) ||
      med.brandNames.some((b) => b.toLowerCase().includes(q)) ||
      med.drugClass.toLowerCase().includes(q) ||
      med.category.toLowerCase().includes(q) ||
      med.diseasesTreated.some((d) => d.toLowerCase().includes(q)) ||
      med.symptomsTreated.some((s) => s.toLowerCase().includes(q)) ||
      med.chemicalFormula.toLowerCase().includes(q)
    );
  });
}
